name: Deploy app on server

on: push

jobs:
  deploy-app:
    name: Deploy app
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
      DEPLOY_USER: ${{secrets.DEPLOY_USER}}
      REDIS_HOST: ${{secrets.REDIS_HOST}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Ssh setup
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa_gh_reader
          chmod 600 ~/.ssh/id_rsa_gh_reader
          ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Build uberjar
        run: lein uberjar

      - name: Overwrite redis host in config file
        run: sed -i '2s/.*/ :redis-host       "'"$REDIS_HOST"'"}/' resources/config.edn

      - name: Transfer uberjar, config file and deploy.sh to server
        run: |
          scp -i ~/.ssh/id_rsa_gh_reader -C target/reader-0.1.0-SNAPSHOT-standalone.jar deployment/deploy.sh "$DEPLOY_USER@$DEPLOY_HOST":/opt
          scp -i ~/.ssh/id_rsa_gh_reader resources/config.edn "$DEPLOY_USER@$DEPLOY_HOST":/opt/resources

      - name: Run deploy script on server
        run: ssh -i ~/.ssh/id_rsa_gh_reader "$DEPLOY_USER@$DEPLOY_HOST" "cd /opt;./deploy.sh"
