name: deploy app on server

on: push

jobs:
  ssh-into-server:
    name: ssh into server
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
      DEPLOY_USER: ${{secrets.DEPLOY_USER}}
    steps:
      - name: ssh setup
        run: |
          eval $(ssh-agent -s)
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: actually ssh in
        run: ssh "$DEPLOY_USER@$DEPLOY_HOST" "cat test.txt"
