name: deploy app on server

on: push

jobs:
  ssh-into-server:
    name: ssh into server
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
      DEPLOY_HOST: ${{secrets.DEPLOY_HOST}}
      DEPLOY_USER: ${{secrets.DEPLOY_USER}}
    steps:
      - name: ssh setup
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa_gh_reader
          ssh-keyscan "$DEPLOY_HOST" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
      - name: actually ssh in
        run: ssh -v -i ~/.ssh/id_rsa_gh_reader "$DEPLOY_USER@$DEPLOY_HOST" "echo hi"
